CREATE USER IF NOT EXISTS 'dev1'@'localhost' IDENTIFIED BY 'devpass';
CREATE USER IF NOT EXISTS 'dev1'@'%' IDENTIFIED BY 'devpass';
GRANT ALL PRIVILEGES ON *.* TO 'dev1'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'dev1'@'%' WITH GRANT OPTION;
CREATE DATABASE IF NOT EXISTS moonbit_dev;
CREATE DATABASE IF NOT EXISTS moonbit_test;
FLUSH PRIVILEGES;